// Generated by gencpp from file lama_msgs/GetCrossing.msg
// DO NOT EDIT!


#ifndef LAMA_MSGS_MESSAGE_GETCROSSING_H
#define LAMA_MSGS_MESSAGE_GETCROSSING_H

#include <ros/service_traits.h>


#include <lama_msgs/GetCrossingRequest.h>
#include <lama_msgs/GetCrossingResponse.h>


namespace lama_msgs
{

struct GetCrossing
{

typedef GetCrossingRequest Request;
typedef GetCrossingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCrossing
} // namespace lama_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lama_msgs::GetCrossing > {
  static const char* value()
  {
    return "4842af2f1edf5a2e9caf0cee19515bcc";
  }

  static const char* value(const ::lama_msgs::GetCrossing&) { return value(); }
};

template<>
struct DataType< ::lama_msgs::GetCrossing > {
  static const char* value()
  {
    return "lama_msgs/GetCrossing";
  }

  static const char* value(const ::lama_msgs::GetCrossing&) { return value(); }
};


// service_traits::MD5Sum< ::lama_msgs::GetCrossingRequest> should match 
// service_traits::MD5Sum< ::lama_msgs::GetCrossing > 
template<>
struct MD5Sum< ::lama_msgs::GetCrossingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lama_msgs::GetCrossing >::value();
  }
  static const char* value(const ::lama_msgs::GetCrossingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lama_msgs::GetCrossingRequest> should match 
// service_traits::DataType< ::lama_msgs::GetCrossing > 
template<>
struct DataType< ::lama_msgs::GetCrossingRequest>
{
  static const char* value()
  {
    return DataType< ::lama_msgs::GetCrossing >::value();
  }
  static const char* value(const ::lama_msgs::GetCrossingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lama_msgs::GetCrossingResponse> should match 
// service_traits::MD5Sum< ::lama_msgs::GetCrossing > 
template<>
struct MD5Sum< ::lama_msgs::GetCrossingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lama_msgs::GetCrossing >::value();
  }
  static const char* value(const ::lama_msgs::GetCrossingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lama_msgs::GetCrossingResponse> should match 
// service_traits::DataType< ::lama_msgs::GetCrossing > 
template<>
struct DataType< ::lama_msgs::GetCrossingResponse>
{
  static const char* value()
  {
    return DataType< ::lama_msgs::GetCrossing >::value();
  }
  static const char* value(const ::lama_msgs::GetCrossingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAMA_MSGS_MESSAGE_GETCROSSING_H
