// Generated by gencpp from file lama_msgs/GetLamaObject.msg
// DO NOT EDIT!


#ifndef LAMA_MSGS_MESSAGE_GETLAMAOBJECT_H
#define LAMA_MSGS_MESSAGE_GETLAMAOBJECT_H

#include <ros/service_traits.h>


#include <lama_msgs/GetLamaObjectRequest.h>
#include <lama_msgs/GetLamaObjectResponse.h>


namespace lama_msgs
{

struct GetLamaObject
{

typedef GetLamaObjectRequest Request;
typedef GetLamaObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLamaObject
} // namespace lama_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lama_msgs::GetLamaObject > {
  static const char* value()
  {
    return "7a0bd86202cd08076ac08c680a875047";
  }

  static const char* value(const ::lama_msgs::GetLamaObject&) { return value(); }
};

template<>
struct DataType< ::lama_msgs::GetLamaObject > {
  static const char* value()
  {
    return "lama_msgs/GetLamaObject";
  }

  static const char* value(const ::lama_msgs::GetLamaObject&) { return value(); }
};


// service_traits::MD5Sum< ::lama_msgs::GetLamaObjectRequest> should match 
// service_traits::MD5Sum< ::lama_msgs::GetLamaObject > 
template<>
struct MD5Sum< ::lama_msgs::GetLamaObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lama_msgs::GetLamaObject >::value();
  }
  static const char* value(const ::lama_msgs::GetLamaObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lama_msgs::GetLamaObjectRequest> should match 
// service_traits::DataType< ::lama_msgs::GetLamaObject > 
template<>
struct DataType< ::lama_msgs::GetLamaObjectRequest>
{
  static const char* value()
  {
    return DataType< ::lama_msgs::GetLamaObject >::value();
  }
  static const char* value(const ::lama_msgs::GetLamaObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lama_msgs::GetLamaObjectResponse> should match 
// service_traits::MD5Sum< ::lama_msgs::GetLamaObject > 
template<>
struct MD5Sum< ::lama_msgs::GetLamaObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lama_msgs::GetLamaObject >::value();
  }
  static const char* value(const ::lama_msgs::GetLamaObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lama_msgs::GetLamaObjectResponse> should match 
// service_traits::DataType< ::lama_msgs::GetLamaObject > 
template<>
struct DataType< ::lama_msgs::GetLamaObjectResponse>
{
  static const char* value()
  {
    return DataType< ::lama_msgs::GetLamaObject >::value();
  }
  static const char* value(const ::lama_msgs::GetLamaObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAMA_MSGS_MESSAGE_GETLAMAOBJECT_H
