// Generated by gencpp from file lama_msgs/SetPlaceProfile.msg
// DO NOT EDIT!


#ifndef LAMA_MSGS_MESSAGE_SETPLACEPROFILE_H
#define LAMA_MSGS_MESSAGE_SETPLACEPROFILE_H

#include <ros/service_traits.h>


#include <lama_msgs/SetPlaceProfileRequest.h>
#include <lama_msgs/SetPlaceProfileResponse.h>


namespace lama_msgs
{

struct SetPlaceProfile
{

typedef SetPlaceProfileRequest Request;
typedef SetPlaceProfileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPlaceProfile
} // namespace lama_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lama_msgs::SetPlaceProfile > {
  static const char* value()
  {
    return "33f8b6a8c5bc01cf725509cfd487af55";
  }

  static const char* value(const ::lama_msgs::SetPlaceProfile&) { return value(); }
};

template<>
struct DataType< ::lama_msgs::SetPlaceProfile > {
  static const char* value()
  {
    return "lama_msgs/SetPlaceProfile";
  }

  static const char* value(const ::lama_msgs::SetPlaceProfile&) { return value(); }
};


// service_traits::MD5Sum< ::lama_msgs::SetPlaceProfileRequest> should match 
// service_traits::MD5Sum< ::lama_msgs::SetPlaceProfile > 
template<>
struct MD5Sum< ::lama_msgs::SetPlaceProfileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lama_msgs::SetPlaceProfile >::value();
  }
  static const char* value(const ::lama_msgs::SetPlaceProfileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lama_msgs::SetPlaceProfileRequest> should match 
// service_traits::DataType< ::lama_msgs::SetPlaceProfile > 
template<>
struct DataType< ::lama_msgs::SetPlaceProfileRequest>
{
  static const char* value()
  {
    return DataType< ::lama_msgs::SetPlaceProfile >::value();
  }
  static const char* value(const ::lama_msgs::SetPlaceProfileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lama_msgs::SetPlaceProfileResponse> should match 
// service_traits::MD5Sum< ::lama_msgs::SetPlaceProfile > 
template<>
struct MD5Sum< ::lama_msgs::SetPlaceProfileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lama_msgs::SetPlaceProfile >::value();
  }
  static const char* value(const ::lama_msgs::SetPlaceProfileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lama_msgs::SetPlaceProfileResponse> should match 
// service_traits::DataType< ::lama_msgs::SetPlaceProfile > 
template<>
struct DataType< ::lama_msgs::SetPlaceProfileResponse>
{
  static const char* value()
  {
    return DataType< ::lama_msgs::SetPlaceProfile >::value();
  }
  static const char* value(const ::lama_msgs::SetPlaceProfileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAMA_MSGS_MESSAGE_SETPLACEPROFILE_H
