// Generated by gencpp from file lama_msgs/SetPlaceProfileRequest.msg
// DO NOT EDIT!


#ifndef LAMA_MSGS_MESSAGE_SETPLACEPROFILEREQUEST_H
#define LAMA_MSGS_MESSAGE_SETPLACEPROFILEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lama_msgs/PlaceProfile.h>

namespace lama_msgs
{
template <class ContainerAllocator>
struct SetPlaceProfileRequest_
{
  typedef SetPlaceProfileRequest_<ContainerAllocator> Type;

  SetPlaceProfileRequest_()
    : descriptor()  {
    }
  SetPlaceProfileRequest_(const ContainerAllocator& _alloc)
    : descriptor(_alloc)  {
    }



   typedef  ::lama_msgs::PlaceProfile_<ContainerAllocator>  _descriptor_type;
  _descriptor_type descriptor;




  typedef boost::shared_ptr< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPlaceProfileRequest_

typedef ::lama_msgs::SetPlaceProfileRequest_<std::allocator<void> > SetPlaceProfileRequest;

typedef boost::shared_ptr< ::lama_msgs::SetPlaceProfileRequest > SetPlaceProfileRequestPtr;
typedef boost::shared_ptr< ::lama_msgs::SetPlaceProfileRequest const> SetPlaceProfileRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lama_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'lama_msgs': ['/lu1/smagri/uni/subj/proj30cp/catkin_ws/src/lama_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f528bce67fe2dc9e2ab90ef5f1e58071";
  }

  static const char* value(const ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf528bce67fe2dc9eULL;
  static const uint64_t static_value2 = 0x2ab90ef5f1e58071ULL;
};

template<class ContainerAllocator>
struct DataType< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lama_msgs/SetPlaceProfileRequest";
  }

  static const char* value(const ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PlaceProfile descriptor\n\
\n\
================================================================================\n\
MSG: lama_msgs/PlaceProfile\n\
# 2D Description of a place by some points at obstacle borders\n\
# The difference with a LaserScan is that some segments can\n\
# be marked as to be excluded. Such segments will be the segments\n\
# where the range is the maximum range of the LaserSCan or\n\
# borders between free and unknown pixels of a costmap.\n\
\n\
Header header\n\
\n\
geometry_msgs/Polygon polygon\n\
\n\
# Segments to exclude, segment i is between point i and i+1.\n\
# The last segment is between points (n-1) and 0, where n is the number of points.\n\
int32[] exclude_segments\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Polygon\n\
#A specification of a polygon where the first and last points are assumed to be connected\n\
Point32[] points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.descriptor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetPlaceProfileRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lama_msgs::SetPlaceProfileRequest_<ContainerAllocator>& v)
  {
    s << indent << "descriptor: ";
    s << std::endl;
    Printer< ::lama_msgs::PlaceProfile_<ContainerAllocator> >::stream(s, indent + "  ", v.descriptor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAMA_MSGS_MESSAGE_SETPLACEPROFILEREQUEST_H
