// Generated by gencpp from file voice_node/voice_node.msg
// DO NOT EDIT!


#ifndef VOICE_NODE_MESSAGE_VOICE_NODE_H
#define VOICE_NODE_MESSAGE_VOICE_NODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voice_node
{
template <class ContainerAllocator>
struct voice_node_
{
  typedef voice_node_<ContainerAllocator> Type;

  voice_node_()
    : txt4TTS()
    , voiceName()  {
    }
  voice_node_(const ContainerAllocator& _alloc)
    : txt4TTS(_alloc)
    , voiceName(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _txt4TTS_type;
  _txt4TTS_type txt4TTS;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _voiceName_type;
  _voiceName_type voiceName;




  typedef boost::shared_ptr< ::voice_node::voice_node_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voice_node::voice_node_<ContainerAllocator> const> ConstPtr;

}; // struct voice_node_

typedef ::voice_node::voice_node_<std::allocator<void> > voice_node;

typedef boost::shared_ptr< ::voice_node::voice_node > voice_nodePtr;
typedef boost::shared_ptr< ::voice_node::voice_node const> voice_nodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voice_node::voice_node_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voice_node::voice_node_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace voice_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'voice_node': ['/lu1/smagri/uni/subj/proj30cp/catkin_ws/src/voice_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::voice_node::voice_node_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_node::voice_node_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_node::voice_node_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_node::voice_node_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_node::voice_node_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_node::voice_node_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voice_node::voice_node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0da82377af97bdc608894b2abce81d56";
  }

  static const char* value(const ::voice_node::voice_node_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0da82377af97bdc6ULL;
  static const uint64_t static_value2 = 0x08894b2abce81d56ULL;
};

template<class ContainerAllocator>
struct DataType< ::voice_node::voice_node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voice_node/voice_node";
  }

  static const char* value(const ::voice_node::voice_node_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voice_node::voice_node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string txt4TTS\n\
string voiceName\n\
";
  }

  static const char* value(const ::voice_node::voice_node_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voice_node::voice_node_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.txt4TTS);
      stream.next(m.voiceName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct voice_node_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voice_node::voice_node_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voice_node::voice_node_<ContainerAllocator>& v)
  {
    s << indent << "txt4TTS: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.txt4TTS);
    s << indent << "voiceName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.voiceName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOICE_NODE_MESSAGE_VOICE_NODE_H
