// Generated by gencpp from file a3_help/RequestGoal.msg
// DO NOT EDIT!


#ifndef A3_HELP_MESSAGE_REQUESTGOAL_H
#define A3_HELP_MESSAGE_REQUESTGOAL_H

#include <ros/service_traits.h>


#include <a3_help/RequestGoalRequest.h>
#include <a3_help/RequestGoalResponse.h>


namespace a3_help
{

struct RequestGoal
{

typedef RequestGoalRequest Request;
typedef RequestGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestGoal
} // namespace a3_help


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::a3_help::RequestGoal > {
  static const char* value()
  {
    return "f6ea81b8d005beee56d00a85ea6bd161";
  }

  static const char* value(const ::a3_help::RequestGoal&) { return value(); }
};

template<>
struct DataType< ::a3_help::RequestGoal > {
  static const char* value()
  {
    return "a3_help/RequestGoal";
  }

  static const char* value(const ::a3_help::RequestGoal&) { return value(); }
};


// service_traits::MD5Sum< ::a3_help::RequestGoalRequest> should match 
// service_traits::MD5Sum< ::a3_help::RequestGoal > 
template<>
struct MD5Sum< ::a3_help::RequestGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::a3_help::RequestGoal >::value();
  }
  static const char* value(const ::a3_help::RequestGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::a3_help::RequestGoalRequest> should match 
// service_traits::DataType< ::a3_help::RequestGoal > 
template<>
struct DataType< ::a3_help::RequestGoalRequest>
{
  static const char* value()
  {
    return DataType< ::a3_help::RequestGoal >::value();
  }
  static const char* value(const ::a3_help::RequestGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::a3_help::RequestGoalResponse> should match 
// service_traits::MD5Sum< ::a3_help::RequestGoal > 
template<>
struct MD5Sum< ::a3_help::RequestGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::a3_help::RequestGoal >::value();
  }
  static const char* value(const ::a3_help::RequestGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::a3_help::RequestGoalResponse> should match 
// service_traits::DataType< ::a3_help::RequestGoal > 
template<>
struct DataType< ::a3_help::RequestGoalResponse>
{
  static const char* value()
  {
    return DataType< ::a3_help::RequestGoal >::value();
  }
  static const char* value(const ::a3_help::RequestGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // A3_HELP_MESSAGE_REQUESTGOAL_H
