set(_CATKIN_CURRENT_PACKAGE "a3_help")
set(a3_help_VERSION "0.0.0")
set(a3_help_MAINTAINER "student <student@todo.todo>")
set(a3_help_PACKAGE_FORMAT "1")
set(a3_help_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "message_generation")
set(a3_help_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "message_runtime")
set(a3_help_BUILDTOOL_DEPENDS "catkin")
set(a3_help_BUILDTOOL_EXPORT_DEPENDS )
set(a3_help_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "message_runtime")
set(a3_help_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs" "message_runtime")
set(a3_help_TEST_DEPENDS )
set(a3_help_DOC_DEPENDS )
set(a3_help_DEPRECATED "")