// Generated by gencpp from file lama_msgs/GetInterfaceInfoRequest.msg
// DO NOT EDIT!


#ifndef LAMA_MSGS_MESSAGE_GETINTERFACEINFOREQUEST_H
#define LAMA_MSGS_MESSAGE_GETINTERFACEINFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lama_msgs
{
template <class ContainerAllocator>
struct GetInterfaceInfoRequest_
{
  typedef GetInterfaceInfoRequest_<ContainerAllocator> Type;

  GetInterfaceInfoRequest_()
    : interface_name()  {
    }
  GetInterfaceInfoRequest_(const ContainerAllocator& _alloc)
    : interface_name(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _interface_name_type;
  _interface_name_type interface_name;




  typedef boost::shared_ptr< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetInterfaceInfoRequest_

typedef ::lama_msgs::GetInterfaceInfoRequest_<std::allocator<void> > GetInterfaceInfoRequest;

typedef boost::shared_ptr< ::lama_msgs::GetInterfaceInfoRequest > GetInterfaceInfoRequestPtr;
typedef boost::shared_ptr< ::lama_msgs::GetInterfaceInfoRequest const> GetInterfaceInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lama_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'lama_msgs': ['/lu1/smagri/uni/subj/proj30cp/catkin_ws/src/lama_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9193059f50f78fd19fabc1ca461cc94";
  }

  static const char* value(const ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9193059f50f78fdULL;
  static const uint64_t static_value2 = 0x19fabc1ca461cc94ULL;
};

template<class ContainerAllocator>
struct DataType< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lama_msgs/GetInterfaceInfoRequest";
  }

  static const char* value(const ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string interface_name\n\
";
  }

  static const char* value(const ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.interface_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetInterfaceInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lama_msgs::GetInterfaceInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "interface_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.interface_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAMA_MSGS_MESSAGE_GETINTERFACEINFOREQUEST_H
