// Generated by gencpp from file lama_msgs/GetPlaceProfile.msg
// DO NOT EDIT!


#ifndef LAMA_MSGS_MESSAGE_GETPLACEPROFILE_H
#define LAMA_MSGS_MESSAGE_GETPLACEPROFILE_H

#include <ros/service_traits.h>


#include <lama_msgs/GetPlaceProfileRequest.h>
#include <lama_msgs/GetPlaceProfileResponse.h>


namespace lama_msgs
{

struct GetPlaceProfile
{

typedef GetPlaceProfileRequest Request;
typedef GetPlaceProfileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlaceProfile
} // namespace lama_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lama_msgs::GetPlaceProfile > {
  static const char* value()
  {
    return "1618b57072692f88573b9b9dff6edef8";
  }

  static const char* value(const ::lama_msgs::GetPlaceProfile&) { return value(); }
};

template<>
struct DataType< ::lama_msgs::GetPlaceProfile > {
  static const char* value()
  {
    return "lama_msgs/GetPlaceProfile";
  }

  static const char* value(const ::lama_msgs::GetPlaceProfile&) { return value(); }
};


// service_traits::MD5Sum< ::lama_msgs::GetPlaceProfileRequest> should match 
// service_traits::MD5Sum< ::lama_msgs::GetPlaceProfile > 
template<>
struct MD5Sum< ::lama_msgs::GetPlaceProfileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lama_msgs::GetPlaceProfile >::value();
  }
  static const char* value(const ::lama_msgs::GetPlaceProfileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lama_msgs::GetPlaceProfileRequest> should match 
// service_traits::DataType< ::lama_msgs::GetPlaceProfile > 
template<>
struct DataType< ::lama_msgs::GetPlaceProfileRequest>
{
  static const char* value()
  {
    return DataType< ::lama_msgs::GetPlaceProfile >::value();
  }
  static const char* value(const ::lama_msgs::GetPlaceProfileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lama_msgs::GetPlaceProfileResponse> should match 
// service_traits::MD5Sum< ::lama_msgs::GetPlaceProfile > 
template<>
struct MD5Sum< ::lama_msgs::GetPlaceProfileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lama_msgs::GetPlaceProfile >::value();
  }
  static const char* value(const ::lama_msgs::GetPlaceProfileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lama_msgs::GetPlaceProfileResponse> should match 
// service_traits::DataType< ::lama_msgs::GetPlaceProfile > 
template<>
struct DataType< ::lama_msgs::GetPlaceProfileResponse>
{
  static const char* value()
  {
    return DataType< ::lama_msgs::GetPlaceProfile >::value();
  }
  static const char* value(const ::lama_msgs::GetPlaceProfileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAMA_MSGS_MESSAGE_GETPLACEPROFILE_H
