// Generated by gencpp from file lama_msgs/LamaObject.msg
// DO NOT EDIT!


#ifndef LAMA_MSGS_MESSAGE_LAMAOBJECT_H
#define LAMA_MSGS_MESSAGE_LAMAOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lama_msgs
{
template <class ContainerAllocator>
struct LamaObject_
{
  typedef LamaObject_<ContainerAllocator> Type;

  LamaObject_()
    : id(0)
    , id_in_world(0)
    , name()
    , emitter_id(0)
    , emitter_name()
    , type(0)
    , references()  {
      references.assign(0);
  }
  LamaObject_(const ContainerAllocator& _alloc)
    : id(0)
    , id_in_world(0)
    , name(_alloc)
    , emitter_id(0)
    , emitter_name(_alloc)
    , type(0)
    , references()  {
      references.assign(0);
  }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _id_in_world_type;
  _id_in_world_type id_in_world;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _emitter_id_type;
  _emitter_id_type emitter_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _emitter_name_type;
  _emitter_name_type emitter_name;

   typedef int32_t _type_type;
  _type_type type;

   typedef boost::array<int32_t, 2>  _references_type;
  _references_type references;


    enum { VERTEX = 1 };
     enum { EDGE = 2 };
 

  typedef boost::shared_ptr< ::lama_msgs::LamaObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lama_msgs::LamaObject_<ContainerAllocator> const> ConstPtr;

}; // struct LamaObject_

typedef ::lama_msgs::LamaObject_<std::allocator<void> > LamaObject;

typedef boost::shared_ptr< ::lama_msgs::LamaObject > LamaObjectPtr;
typedef boost::shared_ptr< ::lama_msgs::LamaObject const> LamaObjectConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lama_msgs::LamaObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lama_msgs::LamaObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lama_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'lama_msgs': ['/lu1/smagri/uni/subj/proj30cp/catkin_ws/src/lama_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lama_msgs::LamaObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lama_msgs::LamaObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lama_msgs::LamaObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lama_msgs::LamaObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lama_msgs::LamaObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lama_msgs::LamaObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lama_msgs::LamaObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2747a1741c10b06140b9673d9018102";
  }

  static const char* value(const ::lama_msgs::LamaObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2747a1741c10b06ULL;
  static const uint64_t static_value2 = 0x140b9673d9018102ULL;
};

template<class ContainerAllocator>
struct DataType< ::lama_msgs::LamaObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lama_msgs/LamaObject";
  }

  static const char* value(const ::lama_msgs::LamaObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lama_msgs::LamaObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# id of lama object in the database, will be unique.\n\
# When adding a vertex into the database, this id will be ignored.\n\
int32 id\n\
\n\
# id of lama object in the world (usage is implementation specific).\n\
int32 id_in_world\n\
\n\
# name of object\n\
string name\n\
\n\
# emitter id and name.\n\
int32 emitter_id\n\
string emitter_name\n\
\n\
# type: \"EDGE\" or \"VERTEX\"\n\
int32 type\n\
int32 VERTEX = 1\n\
int32 EDGE = 2\n\
\n\
# for edges: start and end vertices\n\
# for vertices: not used\n\
int32[2] references\n\
\n\
";
  }

  static const char* value(const ::lama_msgs::LamaObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lama_msgs::LamaObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.id_in_world);
      stream.next(m.name);
      stream.next(m.emitter_id);
      stream.next(m.emitter_name);
      stream.next(m.type);
      stream.next(m.references);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct LamaObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lama_msgs::LamaObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lama_msgs::LamaObject_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "id_in_world: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id_in_world);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "emitter_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.emitter_id);
    s << indent << "emitter_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.emitter_name);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "references[]" << std::endl;
    for (size_t i = 0; i < v.references.size(); ++i)
    {
      s << indent << "  references[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.references[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAMA_MSGS_MESSAGE_LAMAOBJECT_H
